backend:
  name: git-gateway

media_folder: static/assets
public_folder: /assets
publish_mode: editorial_workflow

collections:
  - name: homepage
    label: Homepage
    folder: home
    create: true
    fields:
      - name: sticky
        label: Sticky
        widget: relation
        collection: posts
        searchFields: ["name", "title"]
        valueField: name
      - name: teasers
        label: Teaser
        widget: list
        required: false,
        fields:
          - { name: verticalPosition, label "Vertical Position"  }
          - name: teaser
            label: Teaser
            widget: relation
            collection: posts
            searchFields: ["name", "title"]
            valueField: name
  - name: posts
    label: Post
    folder: post
    create: true
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name location, label: Location, required: false }
      - { name: date, label: Date, widget: date }
      - { name: meta_description, label: Meta Description, widget: "text", required: false }
      - { name: "thumbnail", label: "Featured Image", widget: "image" }
      - label: "Row"
        name: "row"
        widget: "list"
        required: false
        fields:
          - { label: "Vertical Position", name: rowMargin }
          - label: "Row Images"
            name: rowImages
            widget: list
            required: false
            fields:
              - { label: Image, name: image, widget: image }
              - { label: Width, name: width, widget: number, valueType: float, min: 0, max: 100 }
              - { label: "Vertical Position" }
      - { label: "Body", name: "body", widget: "markdown", required: false }
