backend:
  name: git-gateway

editor:
  preview: false

media_folder: static/assets
public_folder: /assets
publish_mode: editorial_workflow

collections:
  - name: category
    label: Category
    folder: category
    create: true
    fields:
      - { name: title, label: Title }
      - label: "Root"
        name: "root"
        widget: "boolean"
      - {label: "Category", name: "category", widget: "hidden", default: false}
      - name: sticky
        label: Sticky
        widget: relation
        collection: posts
        searchFields: ["title"]
        valueField: title
        displayFields: ["title"]
      - name: row
        label: Row
        widget: list
        required: false
        fields:
          - { name: verticalPosition, label: "Vertical Position" }
          - name: teasers
            label: Teaser
            widget: list
            required: false,
            fields:
              - { label: "Vertical Position", name: verticalPosition }
              - { label: Width, name: width, widget: number, valueType: float, min: 0, max: 100 }
              - { label: Indent Left, name: indentLeft, widget: string, default: "0" }
              - { label: Indent Right, name: indentRight, widget: string, default: "0" }
              - name: teaser
                label: Teaser
                widget: relation
                collection: posts
                searchFields: ["title"]
                valueField: title
                displayFields: ["title"]

  - name: posts
    label: Posts
    folder: posts
    create: true
    fields:
      - { name: title, label: Title }
      - { name: location, label: Location, required: false }
      - { name: date, label: Date, widget: date }
      - { name: meta_description, label: Meta Description, widget: "text", required: false }
      - { name: "thumbnail", label: "Featured Image", widget: "image" }
      - {label: "Root", name: "root", widget: "hidden", default: false}
      - {label: "Category", name: "category", widget: "hidden", default: false}
      - label: "Row"
        name: "row"
        widget: "list"
        fields:
          - { label: "Vertical Position", name: verticalPosition, widget: string, default: "0" }
          - label: "Row Images"
            name: rowImages
            widget: list
            fields:
              - { label: "Vertical Position", name: verticalPosition, widget: string, default: "0" }
              - { label: Width, name: width, widget: number, valueType: float, min: 0, max: 100, default: "100" }
              - { label: Indent Left, name: indentLeft, widget: string, default: "0" }
              - { label: Indent Right, name: indentRight, widget: string, default: "0" }
              - { label: Image, name: image, widget: image }
      - { label: "Body", name: "body", widget: "markdown", required: false }
