backend:
  name: git-gateway

media_folder: static/assets
public_folder: /assets
publish_mode: editorial_workflow

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: meta_description, label: Meta Description, widget: "text", required: false }
      - { name: "thumbnail", label: "Featured Image", widget: "image" }
      - label: "Row"
        name: "row"
        widget: "list"
        required: false
        fields:
          - { label: "Vertical Position", name: rowMargin, widget: string }
          - label: "Row Images"
            name: rowImages
            widget: list
            required: false
            fields:
              - { label: Image, name: image, widget: image }
              - { label: Width, name: width, widget: number, valueType: float, min: 0, max: 100 }
              - { label: "Vertical Position", widget: string }
      - { label: "Body", name: "body", widget: "markdown", required: false }
